config/routes.rb
Rabel::Application.routes.draw do
  resources :articles do
    resources :comments
  end

  resources :guides do
    resources :bookmarks
    resources :articles
    get :new_from_home, :on => :collection
    post :create_from_home, :on => :collection
    member do
      get :move
      get :edit_title
      put :update_title
    end
  end

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}
  get 'settings' => 'users#edit'
  get 'member/:nickname' => 'users#show', :as => :member
  get 'member/:nickname/topics' => 'users#topics', :as => :member_topics
  get 'member/:nickname/guides' => 'users#guides', :as => :member_guides
  post 'member/:nickname/follow' => 'users#follow', :as => :follow_user
  post 'member/:nickname/unfollow' => 'users#unfollow', :as => :unfollow_user
  put 'users/update_account' => 'users#update_account', :as => :update_account
  put 'users/update_password' => 'users#update_password', :as => :update_password
  put 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  get 'go/:key' => 'nodes#show', :as => :go
  get 't/:id' => 'topics#show', :as => :t
  get '/topics/:id' => redirect('/t/%{id}'), :constraints => { :id => /\d+/ }

  get '/categories/:id' => redirect('/guides/?c=%{id}'), :constraints => { :id => /\d+/ }

  get 'member/:nickname/marks' => 'users#my_topics', :as => :my_topics
  get 'my/following' => 'users#my_following', :as => :my_following
  get 'page/:key' => 'pages#show', :as => :page
  get 'goodbye' => 'welcome#goodbye'
  get 'captcha' => 'welcome#captcha'
  get 'sitemap' => 'welcome#sitemap'

  get 'users' => 'users#index'

  resources :nodes do
    resources :topics do
      member do
        get :move
        get :edit_title
        put :update_title
      end
    end
  end
  resources :topics do
    resources :comments
    resources :bookmarks
    post :preview, :on => :collection
    put :toggle_comments_closed
    put :toggle_sticky
    get :new_from_home, :on => :collection
  end

  resources :comments, :bookmarks, :upyun_images

  resources :notifications do
    get :read, :on => :member
  end

  namespace :admin do

    resources :categories
    resources :guides

    resources :planes do
      resources :nodes
      post :sort, :on => :collection
      get :sort, :on => :collection
    end

    resources :nodes do
      post :sort, :on => :collection
      get :move, :on => :member
      put :move_to, :on => :member
    end

    resources :users do
      member do
        put :toggle_admin
        put :toggle_blocked
      end
      resources :rewards
    end

    resources :pages do
      post :sort, :on => :collection
    end

    resource :site_settings
    resources :topics, :advertisements, :cloud_files, :rewards

    resources :notifications do
      delete :clear, :on => :collection
    end

    get 'appearance' => 'site_settings#appearance'

    root :to => 'welcome_admin#index'
  end
  root :to => 'welcome#index'

end

app/controllers/topics_controller.rb
# encoding: utf-8
class TopicsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :find_node, :except => [:show, :index, :preview, :toggle_comments_closed, :toggle_sticky, :new_from_home, :create_from_home]
  before_filter :find_topic_and_auth, :only => [:edit_title,:update_title,
    :edit, :update, :move, :destroy]
  before_filter :only => [:toggle_comments_closed, :toggle_sticky] do |c|
    auth_admin
  end

  def index
    respond_to do |format|
      format.html {
        per_page = Siteconf::HOMEPAGE_TOPICS
        @title = '全站最新话题更改记录'
        if params[:page].present?
          current_page = params[:page].to_i
          @title += " (第 #{current_page} 页)"
        else
          current_page = 1
        end

        @topics = Topic.cached_pagination(current_page, per_page, 'updated_at')

        @canonical_path = topics_path
        @canonical_path += "?page=#{current_page}" if current_page > 1

        @seo_description = @title
      }
      format.atom {
        @feed_items = Topic.recent_topics(Siteconf::HOMEPAGE_TOPICS)
        @last_update = @feed_items.first.updated_at unless @feed_items.empty?
        render :layout => false
      }
    end
  end

  def show
    raise ActiveRecord::RecordNotFound.new if params[:id].to_i.to_s != params[:id]

    @topic = Topic.find_cached(params[:id])
    store_location
    # NOTE
    # We can't use @topic.increment!(:hit) here,
    # because updated_at is part of the cache key
    ActiveRecord::Base.connection.execute("UPDATE topics SET hit = hit + 1 WHERE topics.id = #{@topic.id}")

    @title = @topic.title
    @node = @topic.cached_assoc_object(:node)

    @total_comments = @topic.comments_count
    @total_pages = (@total_comments * 1.0 / Siteconf.pagination_comments.to_i).ceil
    @current_page = params[:p].nil? ? @total_pages : params[:p].to_i
    @per_page = Siteconf.pagination_comments.to_i
    @comments = @topic.cached_assoc_pagination(:comments, @current_page, @per_page, 'created_at', Rabel::Model::ORDER_ASC)

    @new_comment = @topic.comments.new
    @total_bookmarks = @topic.bookmarks.count

    @canonical_path = "/t/#{params[:id]}"
    @canonical_path += "?p=#{@current_page}" if @total_pages > 1
    @seo_description = "#{@node.name} - #{@topic.user.nickname} - #{@topic.title}"

    @prev_topic = @topic.prev_topic(@node)
    @next_topic = @topic.next_topic(@node)

    respond_to do |format|
      format.html
      format.mobile
    end
  end

  def new
    @topic = @node.topics.new

    respond_to do |format|
      format.html
      format.mobile
    end
  end

  def new_from_home
    @topic = Topic.new
  end

  def create
    @topic = @node.topics.new(params[:topic], :as => current_user.permission_role)
    @topic.user = current_user
    if @topic.save
      redirect_to t_path(@topic.id)
    else
      render :new
    end
  end

  def create_from_home
    node_id = params[:topic].delete(:node_id)
    @topic = Topic.new(params[:topic], :as => current_user.permission_role)
    @topic.node = Node.find(node_id) if node_id.present?
    @topic.user = current_user

    if @topic.save
      redirect_to t_path(@topic.id)
    else
      render :new_from_home
    end
  end

  def edit_title
    respond_to do |f|
      f.js
    end
  end

  def update_title
    respond_to do |f|
      f.js {
        unless @topic.update_attributes(params[:topic])
          render :text => :error, :status => :unprocessable_entity
        end
      }
    end
  end

  def edit
  end

  def update
    if params[:new_node_id].present?
      # move to new node
      @new_node = Node.find(params[:new_node_id])
      respond_to do |format|
        format.js {
          if @new_node.present?
            @topic.node = @new_node
            if @topic.save
              render :js => "window.location.reload()"
            else
              render :js => "$.facebox('移动帖子失败')"
            end
          else
            render :js => "$.facebox('节点不存在')"
          end
        }
      end
    else
      if @topic.update_attributes(params[:topic], :as => current_user.permission_role)
        redirect_to t_path(@topic.id)
      else
        flash[:error] = '之前的更新有误，请编辑后再提交'
        render :edit
      end
    end
  end

  def move
    respond_to do |format|
      format.js
    end
  end

  def destroy
    if @topic.destroy
      redirect_to root_path, :notice => '帖子删除成功'
    else
      raise RuntimeError.new('删除帖子出错')
    end
  end

  def preview
    @type = ['topic', 'comment', 'page'].delete params[:type]
    respond_to do |f|
      if @type.present?
        f.text { @content = params[:content] }
      else
        render :text => :error, :status => :unprocessable_entity
      end
    end
  end

  def toggle_comments_closed
    @topic = Topic.find(params[:topic_id])
    @topic.toggle!(:comments_closed)
    @topic.touch
    redirect_to t_path(@topic.id)
  end

  def toggle_sticky
    @topic = Topic.find(params[:topic_id])
    @topic.toggle!(:sticky)
    @topic.touch
    redirect_to t_path(@topic.id)
  end

  private
    def find_node
      @node = Node.find(params[:node_id])
    end

    def find_topic_and_auth
      @topic = @node.topics.find(params[:id])
      authorize! :update, @topic, :message => '你没有权限管理此主题'
    end
end

app/views/topics/index.html.haml
- content_for :rightbar do
  = render 'welcome/rightbar_planes'
.box
  .cell
    = build_navigation([@title])
    .pull-right
      = link_to '创建新话题', new_from_home_topics_path, :class => 'btn btn-success btn-sm btn-new-topic'
  = render @topics
  .inner{:align => :center}
    = paginate @topics

app/views/topics/new_from_home.html.slim
- content_for :sidebar do
  .col-md-3.col-lg-3.col-sm-4#Rightbar
    = render 'shared/sidebar_box'
.box
  .cell
    h2 创建新话题
  .inner
    = simple_form_for @topic, :url => create_from_home_topics_path do |f|
      = f.input :title, :label => '标题', :input_html => {:maxlength => 150, :class => :span6}
      = render 'shared/fileupload_widget', :textarea_selector => "textarea#topic_content"
      = render 'shared/preview_widget', :ref => :topic_content, :type => :topic
      = f.input :content, :input_html => {:rows => 10, :style => 'width: 98%;'}, :label => false, :placeholder => '话题内容'
      = f.association :node, :label => false, :collection => Plane.all, :as => :grouped_select, :group_method => :nodes, :prompt => '选择一个节点'
      - if current_user.can_manage_site?
        .checkbox
          = f.input :sticky, :inline_label => '保持置顶', :label => false
        .checkbox
          = f.input :comments_closed, :inline_label => '禁止回复', :label => false
      = f.submit '创建新话题', :class => 'btn btn-primary btn-inverse', :data => {:disable_with => t('tips.submitting')}

app/views/topics/show.html.haml
- content_for :rightbar do
  = render 'welcome/rightbar_planes'
= render 'nodes/custom_fields', :node => @node
= render 'topics/show/bookmarked_users'
= render 'topics/show/manage'

- content_for :template_js do
  :plain
    var creating_comment = false;

    $("textarea#comment_content").keydown(function(e) {
      if (e.ctrlKey && e.keyCode == 13) {
        if (creating_comment) return;
        creating_comment = true
        $("input[type=submit]").click();
      }
    });

- topic_user = @topic.cached_assoc_object(:user)

.box
  %article
    .header
      .pull-right
        = user_profile_avatar_link(topic_user, :large)
      = build_navigation([link_to(@node.name, go_path(@node.key), :class => :rabel)], 'bigger')
      .sep10
      %h1#topic_title
        = Rabel::Base.make_mention_links(Rabel::Base.h(@topic.title)).html_safe
      %small.topic-meta
        By
        = user_profile_link(topic_user, :class => :dark)
        at
        = time_ago_in_words(@topic.created_at)
        ,
        = @topic.hit
        次浏览
      .clearfix
    .inner
      .content.topic_content= format_topic(@topic.content)
      - if user_signed_in?
        .pull-right
          - if current_user.bookmarked?(@topic)
            = link_to '取消收藏', current_user.bookmark_of(@topic), :method => :delete, :class => 'btn btn-xs btn-info unbookmark'
          - else
            = link_to '加入收藏', topic_bookmarks_path(@topic), :method => :post, :class => 'btn btn-xs btn-info bookmark'
      .clearfix
    .inner
      - if @next_topic.present?
        .pull-right
          = link_to proper_length(@next_topic.title, 15), t_path(@next_topic.id), :class => :rabel, :rel => :prev
          %span.guillemet.right-guillemet »

      - if @prev_topic.present?
        .pull-left
          %span.guillemet.left-guillemet «
          = link_to proper_length(@prev_topic.title, 15), t_path(@prev_topic.id), :class => :rabel, :rel => :next
      .clearfix

= render 'topics/show/comments' if @comments.any?

- if @topic.comments_closed?
  = render 'shared/box_tip', :tip => t('tips.comments_closed')
- elsif @comments.empty?
  = render 'shared/box_tip', :tip => '目前尚无回复'

= render 'topics/show/comment_form' unless @topic.comments_closed?