config/routes.rb
Rabel::Application.routes.draw do
  resources :articles do
    resources :comments
  end

  resources :guides do
    resources :bookmarks
    resources :articles
    get :new_from_home, :on => :collection
    post :create_from_home, :on => :collection
    member do
      get :move
      get :edit_title
      put :update_title
    end
  end

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}
  get 'settings' => 'users#edit'
  get 'member/:nickname' => 'users#show', :as => :member
  get 'member/:nickname/topics' => 'users#topics', :as => :member_topics
  get 'member/:nickname/guides' => 'users#guides', :as => :member_guides
  post 'member/:nickname/follow' => 'users#follow', :as => :follow_user
  post 'member/:nickname/unfollow' => 'users#unfollow', :as => :unfollow_user
  put 'users/update_account' => 'users#update_account', :as => :update_account
  put 'users/update_password' => 'users#update_password', :as => :update_password
  put 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  get 'go/:key' => 'nodes#show', :as => :go
  get 't/:id' => 'topics#show', :as => :t
  get '/topics/:id' => redirect('/t/%{id}'), :constraints => { :id => /\d+/ }

  get '/categories/:id' => redirect('/guides/?c=%{id}'), :constraints => { :id => /\d+/ }

  get 'member/:nickname/marks' => 'users#my_topics', :as => :my_topics
  get 'my/following' => 'users#my_following', :as => :my_following
  get 'page/:key' => 'pages#show', :as => :page
  get 'goodbye' => 'welcome#goodbye'
  get 'captcha' => 'welcome#captcha'
  get 'sitemap' => 'welcome#sitemap'

  get 'users' => 'users#index'

  resources :nodes do
    resources :topics do
      member do
        get :move
        get :edit_title
        put :update_title
      end
    end
  end
  resources :topics do
    resources :comments
    resources :bookmarks
    post :preview, :on => :collection
    put :toggle_comments_closed
    put :toggle_sticky
    get :new_from_home, :on => :collection
  end

  resources :comments, :bookmarks, :upyun_images

  resources :notifications do
    get :read, :on => :member
  end

  namespace :admin do

    resources :categories
    resources :guides

    resources :planes do
      resources :nodes
      post :sort, :on => :collection
      get :sort, :on => :collection
    end

    resources :nodes do
      post :sort, :on => :collection
      get :move, :on => :member
      put :move_to, :on => :member
    end

    resources :users do
      member do
        put :toggle_admin
        put :toggle_blocked
      end
      resources :rewards
    end

    resources :pages do
      post :sort, :on => :collection
    end

    resource :site_settings
    resources :topics, :advertisements, :cloud_files, :rewards

    resources :notifications do
      delete :clear, :on => :collection
    end

    get 'appearance' => 'site_settings#appearance'

    root :to => 'welcome_admin#index'
  end
  root :to => 'welcome#index'

end

app/views/shared/_categories.html.haml
.box
  .box-header
    学习教程分类
  .inner
    -Category.cached_all().each do |category|
      =link_to category.title,"#{guides_url}?c=#{category.id}", :class => "rabel item_node"

app/views/shared/_footer.html.haml
#footer
  .container#footer-main
    %ul.page-links
      = render :partial => 'pages/nav', :collection => Page.only_published.default_order, :spacer_template => 'pages/nav_ruler'
    .copywrite
      = Siteconf.footer.html_safe
    %small.muted
      Powered by
      = link_to "MakerLab 创客实验室",root_path
      = "学习系统 基于Rabel"

= render 'shared/google_analytics'

:javascript
  window.rabel.search_engine_url = "#{search_engine_url}";
  jQuery(function($) {
    #{yield :template_js}
  });

:javascript
  #{Siteconf.custom_js.html_safe}

app/views/shared/_my_fav.html.haml
%tr
  %td.with_separator{:width => '34%', :align => :center}
    = link_to my_topics_path(current_user.nickname), :class => :dark, :style => 'display: block;' do
      %span.bigger= current_user.bookmarked_guides_count
      .sep3
      %span.gray 我的学习
  %td.with_separator{:width => '34%', :align => :center}
    = link_to my_topics_path(current_user.nickname), :class => :dark, :style => 'display: block;' do
      %span.bigger= current_user.bookmarked_topics_count
      .sep3
      %span.gray 话题收藏
  %td{:width => '33%', :align => :center}
    = link_to my_following_path, :class => :dark, :style => 'display: block;' do
      %span.bigger= current_user.followed_user_count
      .sep3
      %span.gray 特别关注

app/views/shared/_sidebar_box.html.haml
- if user_signed_in?
  .box
    .cell
      %table
        %tr
          %td{:width => 48, :valign => :top}
            = user_profile_avatar_link(current_user, :medium)
          %td{:width => 10, :valign => :top}
          %td{:width => :auto, :valign => :left}
            .profile-link= user_profile_link(current_user)
            .signature= current_user.account.signature
      .sep10
      %table{:width => '100%'}
        = render 'shared/my_fav'
    - unless current_user.has_avatar?
      .cell
        .muted
          %a{:href => settings_path + "#avatar", :class => 'btn btn-sm btn-info btn-block'} 立刻上传个性头像~
    - if @unread_count > 0
      .inner.muted
        = image_tag 'dot_orange.png', :class => :icon, :align => :top
        = link_to "#{@unread_count} 条未读提醒", notifications_path
- else
  .box
    .cell
      = "#{Siteconf.site_name} — #{Siteconf.short_intro}"
    .inner
      .sep5
      .center
        = link_to '现在注册', new_user_registration_path, :class => 'btn btn-small'
        .sep5
        .sep10
        已注册用户请
        = link_to '登入', new_user_session_path, :class => :rabel

- content_for :rightbar do
  = Siteconf.global_sidebar_block.html_safe

app/views/shared/_sidebar_box_lms.html.haml
- unless user_signed_in?
  .box
    .cell
      = "#{Siteconf.site_name} — #{Siteconf.short_intro}"
    .inner
      .sep5
      .center
        = link_to '现在注册', new_user_registration_path, :class => 'btn btn-small'
        .sep5
        .sep10
        已注册用户请
        = link_to '登入', new_user_session_path, :class => :rabel

- content_for :rightbar do
  = Siteconf.global_sidebar_block.html_safe

app/views/shared/_top.html.haml
#TopMain
  - if Siteconf.custom_logo.present?
    = link_to root_path, :class => 'logo custom_logo' do
      = image_tag Siteconf.custom_logo, :alt => :logo
  - else
    = link_to Siteconf.site_name, root_path, :class => 'logo text_logo'
  #Navigation
    %ul
      %li= link_to '首页', root_path, :class => link_class
      %li= link_to '学习', guides_path, :class => link_class
      %li= link_to '论坛', topics_path, :class => link_class
      - if user_signed_in?
        %li= user_profile_link(current_user, :class => link_class)
        %li= link_to '个人设置', settings_path, :class => link_class
        - if current_user.can_manage_site?
          %li= link_to '管理后台', admin_root_path, :class => link_class
        %li= link_to '登出', destroy_user_session_path, :method => :delete, :class => link_class
      - else
        %li= link_to '注册', new_user_registration_path, :class => link_class
        %li= link_to '登入', new_user_session_path, :class => link_class
  #Search
    .search_input
      %input#q{:type => 'text', :maxlength => 40, :name => 'q', :data => {:domain => Siteconf.site_host}}