config/routes.rb
Rabel::Application.routes.draw do
  resources :articles do
    resources :comments
  end

  resources :guides do
    resources :bookmarks
    resources :articles
    get :new_from_home, :on => :collection
    post :create_from_home, :on => :collection
    member do
      get :move
      get :edit_title
      put :update_title
    end
  end

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}
  get 'settings' => 'users#edit'
  get 'member/:nickname' => 'users#show', :as => :member
  get 'member/:nickname/topics' => 'users#topics', :as => :member_topics
  get 'member/:nickname/guides' => 'users#guides', :as => :member_guides
  post 'member/:nickname/follow' => 'users#follow', :as => :follow_user
  post 'member/:nickname/unfollow' => 'users#unfollow', :as => :unfollow_user
  put 'users/update_account' => 'users#update_account', :as => :update_account
  put 'users/update_password' => 'users#update_password', :as => :update_password
  put 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  get 'go/:key' => 'nodes#show', :as => :go
  get 't/:id' => 'topics#show', :as => :t
  get '/topics/:id' => redirect('/t/%{id}'), :constraints => { :id => /\d+/ }

  get '/categories/:id' => redirect('/guides/?c=%{id}'), :constraints => { :id => /\d+/ }

  get 'member/:nickname/marks' => 'users#my_topics', :as => :my_topics
  get 'my/following' => 'users#my_following', :as => :my_following
  get 'page/:key' => 'pages#show', :as => :page
  get 'goodbye' => 'welcome#goodbye'
  get 'captcha' => 'welcome#captcha'
  get 'sitemap' => 'welcome#sitemap'

  get 'users' => 'users#index'

  resources :nodes do
    resources :topics do
      member do
        get :move
        get :edit_title
        put :update_title
      end
    end
  end
  resources :topics do
    resources :comments
    resources :bookmarks
    post :preview, :on => :collection
    put :toggle_comments_closed
    put :toggle_sticky
    get :new_from_home, :on => :collection
  end

  resources :comments, :bookmarks, :upyun_images

  resources :notifications do
    get :read, :on => :member
  end

  namespace :admin do

    resources :categories
    resources :guides

    resources :planes do
      resources :nodes
      post :sort, :on => :collection
      get :sort, :on => :collection
    end

    resources :nodes do
      post :sort, :on => :collection
      get :move, :on => :member
      put :move_to, :on => :member
    end

    resources :users do
      member do
        put :toggle_admin
        put :toggle_blocked
      end
      resources :rewards
    end

    resources :pages do
      post :sort, :on => :collection
    end

    resource :site_settings
    resources :topics, :advertisements, :cloud_files, :rewards

    resources :notifications do
      delete :clear, :on => :collection
    end

    get 'appearance' => 'site_settings#appearance'

    root :to => 'welcome_admin#index'
  end
  root :to => 'welcome#index'

end

app/models/article.rb
# encoding: utf-8
class Article < ActiveRecord::Base
  include Notifiable
  include Rabel::ActiveCache

  DEFAULT_HIT = 0
  default_value_for :hit, DEFAULT_HIT
  default_value_for :content, ''
  default_value_for :involved_at do
    Time.zone.now
  end

  attr_accessible :title, :content, :complete, :guide_id
  attr_accessible :title, :content, :complete, :guide_id, :comments_closed, :as => :admin
  belongs_to :guide
  belongs_to :user
  has_many :comments, :as => :commentable, :dependent => :destroy
  has_many :notifications, :as => :notifiable, :dependent => :destroy

  validates :guide_id, :user_id, :title, :presence => true

  after_create :send_notifications
  after_save :update_guide

  def last_comment
    self.comments.order('created_at ASC').last
  end

  def allow_modification_by?(user)
    user.can_manage_site?
  end

  def notifiable_title
    self.guide.title + " - " + title
  end

  def notifiable_path
    "/guides/#{self.guide.id}/articles/#{id}"
  end

  def self.latest_involved_topics(num)
    order('involved_at DESC').limit(num).all
  end

  def self.recent_topics(num)
    ts = select('updated_at').order('updated_at DESC').first.try(:updated_at)
    return Rabel::Model::EMPTY_DATASET unless ts.present?
    Rails.cache.fetch("topics/recent/#{self.count}/#{num}-#{ts}") do
      order('involved_at DESC').limit(num).all
    end
  end

  def mention_check_text
    self.title + self.content
  end

  def mentioned_users
    mentioned_names = self.mention_check_text.scan(Notifiable::MENTION_REGEXP).collect {|matched| matched.first}.uniq
    mentioned_names.delete(self.user.nickname)
    mentioned_names.map { |name| User.find_by_nickname(name) }.compact
  end

  def prev_article(guide)
    guide.articles.where(['id < ?', self.id]).order('created_at DESC').first
  end

  def next_article(guide)
    guide.articles.where(['id > ?', self.id]).order('created_at ASC').first
  end

  private

    def send_notifications
      mentioned_users.each do |user|
        Notification.notify(
          user,
          self,
          self.user,
          Notification::ACTION_TOPIC,
          self.content
        )
      end
    end

    def update_guide
      self.guide.touch
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :get_guide, :except => [:show]
  before_filter :except => [:index, :show] do |c|
    auth_admin
  end
  # GET /articles
  # GET /articles.json
  def index
    respond_to do |format|
      format.html {
        @title = @guide.title
        @articles = @guide.articles.cached_all()
        @seo_description = @title
      }
#      format.atom {
#        @feed_items = Topic.recent_topics(Siteconf::HOMEPAGE_TOPICS)
#        @last_update = @feed_items.first.updated_at unless @feed_items.empty?
#        render :layout => false
#      }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    raise ActiveRecord::RecordNotFound.new if params[:id].to_i.to_s != params[:id]

    @article = Article.find_cached(params[:id])
    @current_article_id = @article.id
    store_location
    # NOTE
    # We can't use @topic.increment!(:hit) here,
    # because updated_at is part of the cache key
    ActiveRecord::Base.connection.execute("UPDATE articles SET hit = hit + 1 WHERE articles.id = #{@article.id}")

    @title = @article.title
    @guide = @article.cached_assoc_object(:guide)

    @total_comments = @article.comments_count
    @total_pages = (@total_comments * 1.0 / Siteconf.pagination_comments.to_i).ceil
    @current_page = params[:p].nil? ? @total_pages : params[:p].to_i
    @per_page = Siteconf.pagination_comments.to_i
    @comments = @article.cached_assoc_pagination(:comments, @current_page, @per_page, 'created_at', Rabel::Model::ORDER_ASC)

    @new_comment = @article.comments.new

    @canonical_path = "/guides/#{@guide.id}/articles/#{params[:id]}"
    @canonical_path += "?p=#{@current_page}" if @total_pages > 1
    @seo_description = "#{@guide.title} - #{@guide.user.nickname} - #{@article.title}"

    @prev_article = @article.prev_article(@guide)
    @next_article = @article.next_article(@guide)

    respond_to do |format|
      format.html
      format.mobile
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = @guide.articles.new(params[:article])
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @guide}
      else
        render :new
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private

  def get_guide
    @guide = Guide.find(params[:guide_id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/show/_bookmark_button.html.haml
- if user_signed_in?
  .inner
    .fr{:align => :right}
      - if current_user.bookmarked?(@topic)
        = link_to '取消收藏', current_user.bookmark_of(@topic), :method => :delete, :class => 'op cancel'
      - else
        = link_to '加入收藏', topic_bookmarks_path(@topic), :method => :post, :class => :op
    &nbsp;&nbsp;

app/views/articles/show/_bookmarked_users.html.haml
- if @total_bookmarks > 0
  - content_for :rightbar do
    .box
      .box-header
        收藏此话题的成员
      .inner
        - @topic.bookmarks.each do |b|
          = user_profile_avatar_link(b.user, :mini)

app/views/articles/show/_comment_form.html.haml
- if user_signed_in?
  = form_for [@article, @new_comment] do |f|
    .box
      .box-header
        .fr
          ⬆
          = link_to '回到顶部', 'javascript:void(0);', :class => 'dark back_to_top'
        现在就添加一条回复
      .inner
        = render 'shared/fileupload_widget', :textarea_selector => "textarea#comment_content"
        = render 'shared/preview_widget', :ref => :comment_content, :type => :comment
        = f.text_area :content, :rows => 5, :style => 'width: 98%;'
        .sep10
        = f.submit '发送', :class => 'btn btn-sm btn-success', :data => {:disable_with => t('tips.submitting')}
        %small.gray 支持 Ctrl + Enter 快捷键

app/views/articles/show/_comments.html.haml
%section
  .box
    .box-header
      .fr
        - if @article.comments_closed?
          回复权限关闭
        - else
          ⬇
          = link_to '跳到回复', 'javascript:void(0);', :class => 'dark jump_to_comment'
      = "#{@total_comments} 回复"
    #replies{:class => "#{'fix_cell' if @total_pages == 1}"}
      = render @comments
    - if @total_pages > 1
      = paginate @comments, :param_name => :p

app/views/articles/show/_manage.html.haml
- if can? :update, @article
  - content_for :rightbar do
    .box
      .box-header
        话题管理
      .cell
        = link_to '修改标题', edit_title_node_topic_path(@node, @topic), :remote => true, :class => :btn
        = link_to '编辑全部', edit_node_topic_path(@node, @topic), :class => :btn
      .cell
        = link_to '移动到新节点', move_node_topic_path(@node, @topic), :remote => true, :class => :btn
      - if current_user.can_manage_site?
        .cell
          - toggle_comments_closed_tip = @topic.comments_closed? ? '允许回复' : '禁止回复'
          = link_to toggle_comments_closed_tip, topic_toggle_comments_closed_path(@topic), :method => :put, :class => :btn
          - toggle_sticky_tip = @topic.sticky? ? '取消置顶' : '置顶此话题'
          = link_to toggle_sticky_tip, topic_toggle_sticky_path(@topic), :method => :put, :class => :btn
      .inner
        = link_to '删除此话题', node_topic_path(@node, @topic), :method => :delete, :data => {:confirm => t(:delete_confirm)}, :class => 'btn btn-sm btn-danger'