config/routes.rb
Rabel::Application.routes.draw do
  resources :articles do
    resources :comments
  end

  resources :guides do
    resources :bookmarks
    resources :articles
    get :new_from_home, :on => :collection
    post :create_from_home, :on => :collection
    member do
      get :move
      get :edit_title
      put :update_title
    end
  end

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}
  get 'settings' => 'users#edit'
  get 'member/:nickname' => 'users#show', :as => :member
  get 'member/:nickname/topics' => 'users#topics', :as => :member_topics
  get 'member/:nickname/guides' => 'users#guides', :as => :member_guides
  post 'member/:nickname/follow' => 'users#follow', :as => :follow_user
  post 'member/:nickname/unfollow' => 'users#unfollow', :as => :unfollow_user
  put 'users/update_account' => 'users#update_account', :as => :update_account
  put 'users/update_password' => 'users#update_password', :as => :update_password
  put 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  get 'go/:key' => 'nodes#show', :as => :go
  get 't/:id' => 'topics#show', :as => :t
  get '/topics/:id' => redirect('/t/%{id}'), :constraints => { :id => /\d+/ }

  get '/categories/:id' => redirect('/guides/?c=%{id}'), :constraints => { :id => /\d+/ }

  get 'member/:nickname/marks' => 'users#my_topics', :as => :my_topics
  get 'my/following' => 'users#my_following', :as => :my_following
  get 'page/:key' => 'pages#show', :as => :page
  get 'goodbye' => 'welcome#goodbye'
  get 'captcha' => 'welcome#captcha'
  get 'sitemap' => 'welcome#sitemap'

  get 'users' => 'users#index'

  resources :nodes do
    resources :topics do
      member do
        get :move
        get :edit_title
        put :update_title
      end
    end
  end
  resources :topics do
    resources :comments
    resources :bookmarks
    post :preview, :on => :collection
    put :toggle_comments_closed
    put :toggle_sticky
    get :new_from_home, :on => :collection
  end

  resources :comments, :bookmarks, :upyun_images

  resources :notifications do
    get :read, :on => :member
  end

  namespace :admin do

    resources :categories
    resources :guides

    resources :planes do
      resources :nodes
      post :sort, :on => :collection
      get :sort, :on => :collection
    end

    resources :nodes do
      post :sort, :on => :collection
      get :move, :on => :member
      put :move_to, :on => :member
    end

    resources :users do
      member do
        put :toggle_admin
        put :toggle_blocked
      end
      resources :rewards
    end

    resources :pages do
      post :sort, :on => :collection
    end

    resource :site_settings
    resources :topics, :advertisements, :cloud_files, :rewards

    resources :notifications do
      delete :clear, :on => :collection
    end

    get 'appearance' => 'site_settings#appearance'

    root :to => 'welcome_admin#index'
  end
  root :to => 'welcome#index'

end

app/models/category.rb
# encoding: utf-8
class Category < ActiveRecord::Base
  include Rabel::ActiveCache
  attr_accessible :title, :presence => true

  has_many :guides, :dependent => :destroy

  def can_delete?
    self.guides.count == 0
  end

end

app/controllers/admin/categories_controller.rb
# encoding: utf-8
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
    @title = '教程分类'
  end

  def new
    @category = Category.new
    respond_to do |format|
      format.js {
        @title = '添加教程分类'
        render :show_form
      }
    end
  end

  def create
    @category = Category.new(params[:category])
    respond_to do |format|
      if @category.save
        format.js
      else
        format.js { render :show_form }
      end
    end
  end

  def edit
    @category = Category.find(params[:id])
    respond_to do |format|
      format.js {
        @title = '修改分类'
        render :show_form
      }
    end
  end

  def update
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.js { render :js => 'window.location.reload()' }
      else
        format.js { render :show_form }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.can_delete? and @category.destroy
        format.js
      else
        format.js { render :text => :error, :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<% @categories.each do |category| %>
  <div class="category float-left">
    <%= link_to category.title, category %> | 
    <% if can? :update,@categories %>
      <p><%= link_to 'Edit', edit_category_path(category) %> | 
      <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>
  </div>
<% end %>

<br />

<% if can? :update,@categories %>
  <%= link_to 'New Category', new_category_path %>
<% end %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% content_for(:title) { "MakerLab学习系统-"+@category.title.to_s } %>

<h5>
  <%= link_to "All",root_path %> >
  <%= @category.title %>
</h5>
<% if can? :update,@category %>
  <%= link_to 'New Guide', new_guide_path %>
<% end %>

<div id="masonry-container" class="transitions-enabled has-gutters clearfix">
  <% @guides.each do |guide| %>
    <div class="box-guide ">
      <%= link_to  guide do %>
        <h3><%= guide.title %></h3>
        <h5><%= guide.subtitle %></h5>
        <%= image_tag guide.img unless guide.img.empty? %>
        <p><%= guide.overview %></p>
      <% end %>
    </div>
  <% end %>
</div>

<br />


<script>
var $container = $('#masonry-container').masonry();
$container.imagesLoaded( function(){

  $container.masonry({
    itemSelector: '.box-guide',
    columnWidth: 215,
    gutterWidth: 30
  });

});
</script>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>